sudo: required
dist: trusty

language: python

python:
  - "2.7_with_system_site_packages"

env:
  - TOX_ENV=py27
  - TOX_ENV=flake8

before_install:
  - "wget -q -O - https://apt.mopidy.com/mopidy.gpg | sudo apt-key add -"
  - "sudo wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/jessie.list"
  - "sudo apt-get update -qq"
  - "sudo apt-get install -y gir1.2-gst-plugins-base-1.0 gir1.2-gstreamer-1.0 python-gst-1.0 libffi-dev libspotify-dev python-all-dev"

install:
  - "pip install tox"

script:
  - "tox -e $TOX_ENV"

after_success:
  - "if [ $TOX_ENV == 'py27' ]; then pip install coveralls; coveralls; fi"

branches:
  except:
    - debian

notifications:
  irc:
    channels:
      - "irc.freenode.org#mopidy"
    on_success: change
    on_failure: change
    use_notice: true
    skip_join: true
